import express from 'express';
import cors from 'cors';
import path from 'path';
import { fileURLToPath } from 'url';
import { Resend } from 'resend';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
app.use(cors());
app.use(express.json());

// Initialize Resend with API Key from environment variables
const resend = new Resend(process.env.RESEND_API_KEY);

// Test Email Endpoint
app.post('/api/test-email', async (req, res) => {
  const { email } = req.body;
  try {
    const { data, error } = await resend.emails.send({
      from: 'ShopMaster <onboarding@resend.dev>',
      to: email || 'mdronytalukder42@gmail.com',
      subject: 'ShopMaster Connection Test',
      text: 'Your email system is live and working with Resend!',
    });

    if (error) {
      return res.status(400).json({ success: false, error });
    }

    res.status(200).json({ success: true, data });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// Sends invoice to Customer AND Owner
app.post('/api/send-invoice', async (req, res) => {
  const { email, adminEmail, saleId, shopName, customerName, date, description, total, paid, due } = req.body;
  
  const recipients = [adminEmail || 'mdronytalukder42@gmail.com'];
  if (email && email.trim() !== "") recipients.push(email);

  try {
    const { data, error } = await resend.emails.send({
      from: `${shopName} <onboarding@resend.dev>`,
      to: recipients,
      subject: `New Invoice #${saleId} - ${shopName}`,
      html: `
        <div style="font-family: Arial, sans-serif; padding: 25px; border: 1px solid #e2e8f0; border-radius: 20px; max-width: 600px; margin: auto;">
          <h2 style="color: #4f46e5; text-align: center; margin-bottom: 5px;">${shopName}</h2>
          <p style="text-align: center; color: #64748b; font-size: 14px; margin-top: 0;">Automated Sales Receipt</p>
          <hr style="border: 0; border-top: 1px solid #f1f5f9; margin: 20px 0;">
          <table style="width: 100%; font-size: 14px; color: #334155;">
            <tr><td><strong>Invoice:</strong> #${saleId}</td><td style="text-align: right;"><strong>Date:</strong> ${date}</td></tr>
            <tr><td colspan="2" style="padding-top: 10px;"><strong>Customer:</strong> ${customerName}</td></tr>
          </table>
          <div style="background: #f8fafc; padding: 15px; border-radius: 12px; margin: 20px 0; font-size: 14px; color: #475569;">
            <strong>Items:</strong><br>${description.replace(/\n/g, '<br>')}
          </div>
          <table style="width: 100%; font-size: 16px; border-collapse: collapse;">
            <tr style="border-bottom: 1px solid #f1f5f9;"><td style="padding: 10px 0;">Total Bill:</td><td style="text-align: right; font-weight: bold;">৳${total}</td></tr>
            <tr style="border-bottom: 1px solid #f1f5f9;"><td style="padding: 10px 0;">Paid Amount:</td><td style="text-align: right; color: #10b981; font-weight: bold;">৳${paid}</td></tr>
            <tr><td style="padding: 10px 0; font-size: 18px; font-weight: 900;">Due Balance:</td><td style="text-align: right; color: #ef4444; font-size: 18px; font-weight: 900;">৳${due}</td></tr>
          </table>
          <p style="text-align: center; margin-top: 30px; font-size: 11px; color: #94a3b8; text-transform: uppercase; letter-spacing: 1px;">Generated by ShopMaster Pro</p>
        </div>
      `
    });

    if (error) {
      return res.status(400).json({ success: false, error });
    }

    res.status(200).json({ success: true, data });
  } catch (error) {
    console.error("Email Error:", error);
    res.status(500).json({ success: false, error: "Resend Error" });
  }
});

// Notify admin of edit requests
app.post('/api/notify-admin', async (req, res) => {
  const { adminEmail, requestId, entityType, field, requestedBy, reason } = req.body;
  
  try {
    const { data, error } = await resend.emails.send({
      from: 'ShopMaster System <onboarding@resend.dev>',
      to: adminEmail || 'mdronytalukder42@gmail.com',
      subject: `New Edit Request: ${entityType} - ${field}`,
      html: `
        <div style="font-family: Arial, sans-serif; padding: 25px; border: 1px solid #e2e8f0; border-radius: 20px; max-width: 600px; margin: auto;">
          <h2 style="color: #4f46e5; text-align: center;">New Approval Request</h2>
          <p style="color: #64748b;">A new correction request has been submitted and requires your review.</p>
          <hr style="border: 0; border-top: 1px solid #f1f5f9; margin: 20px 0;">
          <ul style="list-style: none; padding: 0; font-size: 14px; color: #334155;">
            <li><strong>Request ID:</strong> ${requestId}</li>
            <li><strong>Entity:</strong> ${entityType}</li>
            <li><strong>Field:</strong> ${field}</li>
            <li><strong>Requested By:</strong> ${requestedBy}</li>
          </ul>
          <div style="background: #fffbeb; padding: 15px; border-radius: 12px; margin: 20px 0; font-size: 14px; color: #92400e; border: 1px solid #fef3c7;">
            <strong>Reason:</strong><br>${reason}
          </div>
          <p style="text-align: center; font-size: 11px; color: #94a3b8; text-transform: uppercase;">Review this in the Admin Approvals panel.</p>
        </div>
      `
    });

    if (error) {
      return res.status(400).json({ success: false, error });
    }

    res.status(200).json({ success: true, data });
  } catch (error) {
    console.error("Email Error:", error);
    res.status(500).json({ success: false, error: "Resend Error" });
  }
});

// Placeholder for SMS (You can integrate a cheaper provider here later)
app.post('/api/send-sms', async (req, res) => {
  const { to, message } = req.body;
  console.log(`SMS to ${to}: ${message}`);
  // For now, we'll just simulate success to avoid errors
  res.status(200).json({ success: true, simulated: true });
});

// Serve static files from the Vite build directory
app.use(express.static(path.join(__dirname, 'dist')));

// Handle SPA routing
app.get('*', (req, res) => {
  if (!req.path.startsWith('/api/')) {
    res.sendFile(path.join(__dirname, 'dist', 'index.html'));
  }
});

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server Running on Port ${PORT}`));
